/**
 * Pre-bundled initial dataset from Recensement S9 Google Sheet
 * Auto-generated with intelligent title note extraction.
 */
export const INITIAL_DATA = {
  "sheetUpdateDate": "21/09/2026",
  "generatedAt": "2026-09-21T19:47:56.888Z",
  "courses": [
  {
    "id": "c_001",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Uterus cicatriciel",
    "badges": [],
    "questions": 11,
    "weight": 0.49,
    "rawTitle": "Uterus cicatriciel",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_002",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Le retard de croissance intra-utérine RCIU",
    "badges": [],
    "questions": 18,
    "weight": 0.81,
    "rawTitle": "Le retard de croissance intra-utérine RCIU",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_003",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "les infections génitales",
    "badges": [],
    "questions": 36,
    "weight": 1.62,
    "rawTitle": "les infections génitales",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_004",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Cancer de la vulve",
    "badges": [],
    "questions": 8,
    "weight": 0.36,
    "rawTitle": "Cancer de la vulve",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_005",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Infections urinaires et grossesse",
    "badges": [],
    "questions": 26,
    "weight": 1.17,
    "rawTitle": "Infections urinaires et grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_006",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Toxoplasmose et grossesse",
    "badges": [],
    "questions": 17,
    "weight": 0.76,
    "rawTitle": "Toxoplasmose et grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_007",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Rubéole et grossesse",
    "badges": [],
    "questions": 7,
    "weight": 0.31,
    "rawTitle": "Rubéole et grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_008",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Streptocoque B et grossesse",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "Streptocoque B et grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_009",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Errarhay",
    "title": "Les suites de couches normales et pathologiques",
    "badges": [],
    "questions": 23,
    "weight": 1.03,
    "rawTitle": "Les suites de couches normales et pathologiques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_010",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "Cancer du sein",
    "badges": [],
    "questions": 47,
    "weight": 2.11,
    "rawTitle": "Cancer du sein",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_011",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "Cancer de l'ovaire",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Cancer de l'ovaire",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_012",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "Grossesse extra-utérine",
    "badges": [],
    "questions": 25,
    "weight": 1.12,
    "rawTitle": "Grossesse extra-utérine",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_013",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "Les Maladies trophoblastiques Gestationnelles",
    "badges": [],
    "questions": 31,
    "weight": 1.39,
    "rawTitle": "Les Maladies trophoblastiques Gestationnelles",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_014",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "Les avortements",
    "badges": [],
    "questions": 8,
    "weight": 0.36,
    "rawTitle": "Les avortements",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_015",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "La rupture prématurée des membranes",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "La rupture prématurée des membranes",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_016",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Bouchikhi",
    "title": "La délivrance normale et pathologique",
    "badges": [],
    "questions": 24,
    "weight": 1.08,
    "rawTitle": "La délivrance normale et pathologique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_017",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Fdili",
    "title": "Diagnostic et surveillance de la grossesse",
    "badges": [],
    "questions": 21,
    "weight": 0.94,
    "rawTitle": "Diagnostic et surveillance de la grossesse",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_018",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Fdili",
    "title": "Hémorragies du 3ème trimestre",
    "badges": [],
    "questions": 29,
    "weight": 1.3,
    "rawTitle": "Hémorragies du 3ème trimestre",
    "facultyStatus": "En cours",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_019",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Fdili",
    "title": "Présentations défléchies",
    "badges": [],
    "questions": 25,
    "weight": 1.12,
    "rawTitle": "Présentations défléchies",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_020",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "Diabète et grossesse",
    "badges": [],
    "questions": 24,
    "weight": 1.08,
    "rawTitle": "Diabète et grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_021",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "Pré-éclampsie",
    "badges": [],
    "questions": 21,
    "weight": 0.94,
    "rawTitle": "Pré-éclampsie",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_022",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "Allo-immunisations foeto-maternelles: Rhésus",
    "badges": [],
    "questions": 18,
    "weight": 0.81,
    "rawTitle": "Allo-immunisations foeto-maternelles: Rhésus",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_023",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "La grossesse gémellaire",
    "badges": [],
    "questions": 16,
    "weight": 0.72,
    "rawTitle": "La grossesse gémellaire",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_024",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "La menace d’accouchement prématuré",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "La menace d’accouchement prématuré",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_025",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Chaara",
    "title": "La souffrance foetale aiguë",
    "badges": [
      {
        "type": "faculty_note",
        "text": "Note: devenue asphyxie +++",
        "icon": "info",
        "bg": "bg-purple-50",
        "textCol": "text-purple-700",
        "border": "border-purple-200"
      }
    ],
    "questions": 6,
    "weight": 0.27,
    "rawTitle": "La souffrance foetale aiguë > devenue asphyxie +++",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_026",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "Accouchement normal",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "Accouchement normal",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_027",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "presentation de siege",
    "badges": [],
    "questions": 15,
    "weight": 0.67,
    "rawTitle": "presentation de siege",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_028",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "Dysplasies cervicales",
    "badges": [],
    "questions": 9,
    "weight": 0.4,
    "rawTitle": "Dysplasies cervicales",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_029",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "Les fibromes utérins",
    "badges": [],
    "questions": 21,
    "weight": 0.94,
    "rawTitle": "Les fibromes utérins",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_030",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "Cancer du col uterin",
    "badges": [],
    "questions": 27,
    "weight": 1.21,
    "rawTitle": "Cancer du col uterin",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_031",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. Melhouf",
    "title": "Le cancer de l'endomètre",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "Le cancer de l'endomètre",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_032",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. S.Jayi",
    "title": "Endometrioses",
    "badges": [],
    "questions": 2,
    "weight": 0.09,
    "rawTitle": "Endometrioses",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_033",
    "module": "GYNECO-OBSTETRIQUE",
    "submodule": "Gynécologie - Obstétrique",
    "prof": "Pr. S.Jayi",
    "title": "Abord du couple infertile",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "Abord du couple infertile",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_034",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Moutei",
    "title": "Anatomie et physiologie de la vision",
    "badges": [],
    "questions": 10,
    "weight": 0.45,
    "rawTitle": "Anatomie et physiologie de la vision",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_035",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Moutei",
    "title": "Examen clinique en ophtalmologie",
    "badges": [],
    "questions": 22,
    "weight": 0.99,
    "rawTitle": "Examen clinique en ophtalmologie",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_036",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Moutei",
    "title": "Conduite à tenir devant un oeil rouge",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Conduite à tenir devant un oeil rouge",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_037",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Moutei",
    "title": "Conduite à tenir devant une baisse de l’acuité visuelle",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Conduite à tenir devant une baisse de l’acuité visuelle",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_038",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Chraibi",
    "title": "Les conjonctivites",
    "badges": [],
    "questions": 10,
    "weight": 0.45,
    "rawTitle": "Les conjonctivites",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "21/09/2026"
  },
  {
    "id": "c_039",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Chraibi",
    "title": "Les kératites",
    "badges": [],
    "questions": 5,
    "weight": 0.22,
    "rawTitle": "Les kératites",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_040",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Abdellaoui",
    "title": "Les manifestations oculaires liées au diabète",
    "badges": [],
    "questions": 67,
    "weight": 3.01,
    "rawTitle": "Les manifestations oculaires liées au diabète",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_041",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Abdellaoui",
    "title": "Le décollement de la rétine rhegmatogène",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Le décollement de la rétine rhegmatogène",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_042",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Abdellaoui",
    "title": "La dégénérescence maculaire liées à l'âge",
    "badges": [],
    "questions": 24,
    "weight": 1.08,
    "rawTitle": "La dégénérescence maculaire liées à l'âge",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_043",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Abdellaoui",
    "title": "L’uvéite",
    "badges": [],
    "questions": 21,
    "weight": 0.94,
    "rawTitle": "L’uvéite",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_044",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Abdellaoui",
    "title": "Les strabismes",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Les strabismes",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_045",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "Leucocorie",
    "badges": [],
    "questions": 0,
    "weight": 0,
    "rawTitle": "Leucocorie",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_046",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "Les traumatismes oculo-orbitaires",
    "badges": [],
    "questions": 17,
    "weight": 0.76,
    "rawTitle": "Les traumatismes oculo-orbitaires",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_047",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "CAT devant une exophtalmie",
    "badges": [],
    "questions": 26,
    "weight": 1.17,
    "rawTitle": "CAT devant une exophtalmie",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_048",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "CAT devant un larmoiement",
    "badges": [],
    "questions": 30,
    "weight": 1.35,
    "rawTitle": "CAT devant un larmoiement",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_049",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "Les amétropies",
    "badges": [],
    "questions": 22,
    "weight": 0.99,
    "rawTitle": "Les amétropies",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_050",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "Les cataractes",
    "badges": [],
    "questions": 32,
    "weight": 1.44,
    "rawTitle": "Les cataractes",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_051",
    "module": "ORL - OPHTALMO",
    "submodule": "Ophtalmologie",
    "prof": "Pr. Benatiya",
    "title": "Les glaucomes",
    "badges": [],
    "questions": 30,
    "weight": 1.35,
    "rawTitle": "Les glaucomes",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_052",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Benmansour",
    "title": "Otites externes et otites moyennes aigues",
    "badges": [
      {
        "type": "new",
        "text": "Nouveau cours",
        "icon": "sparkles",
        "bg": "bg-blue-50",
        "textCol": "text-blue-700",
        "border": "border-blue-200"
      }
    ],
    "questions": 30,
    "weight": 1.35,
    "rawTitle": "Otites externes et otites moyennes aigues (nouveau cours)",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_053",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Benmansour",
    "title": "otites moyennes chroniques",
    "badges": [],
    "questions": 25,
    "weight": 1.12,
    "rawTitle": "otites moyennes chroniques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_054",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Benmansour",
    "title": "paralysie faciale",
    "badges": [],
    "questions": 25,
    "weight": 1.12,
    "rawTitle": "paralysie faciale",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_055",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Ridal",
    "title": "Les sinusites",
    "badges": [
      {
        "type": "new",
        "text": "Nouveau cours",
        "icon": "sparkles",
        "bg": "bg-blue-50",
        "textCol": "text-blue-700",
        "border": "border-blue-200"
      }
    ],
    "questions": 26,
    "weight": 1.17,
    "rawTitle": "Les sinusites (nouveau cours)",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_056",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Ridal",
    "title": "Les angines",
    "badges": [],
    "questions": 16,
    "weight": 0.72,
    "rawTitle": "Les angines",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_057",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Ridal",
    "title": "Nodules thyroidiens",
    "badges": [],
    "questions": 20,
    "weight": 0.9,
    "rawTitle": "Nodules thyroidiens",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_058",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Ouatassi",
    "title": "Les surdités",
    "badges": [],
    "questions": 22,
    "weight": 0.99,
    "rawTitle": "Les surdités",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_059",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Ouatassi",
    "title": "La rhinite allergique",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "La rhinite allergique",
    "facultyStatus": "En cours",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_060",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Laamarti",
    "title": "Les vertiges",
    "badges": [
      {
        "type": "changed",
        "text": "Cours changé",
        "icon": "alert-circle",
        "bg": "bg-amber-50",
        "textCol": "text-amber-800",
        "border": "border-amber-200"
      }
    ],
    "questions": 41,
    "weight": 1.84,
    "rawTitle": "Les vertiges (cours changé)",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_061",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Afellah",
    "title": "SAOS",
    "badges": [
      {
        "type": "new",
        "text": "Nouveau cours",
        "icon": "sparkles",
        "bg": "bg-blue-50",
        "textCol": "text-blue-700",
        "border": "border-blue-200"
      }
    ],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "SAOS (nouveau cours)",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_062",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Zaki",
    "title": "Les cancers du cavum et des voies aéro-digestives sup",
    "badges": [],
    "questions": 35,
    "weight": 1.57,
    "rawTitle": "Les cancers du cavum et des voies aéro-digestives sup",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_063",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Kamal",
    "title": "Les cellulites cervico-faciales",
    "badges": [],
    "questions": 9,
    "weight": 0.4,
    "rawTitle": "Les cellulites cervico-faciales",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_064",
    "module": "ORL - OPHTALMO",
    "submodule": "ORL",
    "prof": "Pr. Kamal",
    "title": "Les traumatismes maxillo-faciaux",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "Les traumatismes maxillo-faciaux",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_065",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "Epidémiologie générale",
    "badges": [],
    "questions": 20,
    "weight": 0.9,
    "rawTitle": "Epidémiologie générale",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "21/09/2026"
  },
  {
    "id": "c_066",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "Les indicateurs de santé",
    "badges": [],
    "questions": 14,
    "weight": 0.63,
    "rawTitle": "Les indicateurs de santé",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_067",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "Les enquêtes épidémiologiques",
    "badges": [],
    "questions": 42,
    "weight": 1.89,
    "rawTitle": "Les enquêtes épidémiologiques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_068",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "les sources d'erreurs et de biais en épidémiologie",
    "badges": [],
    "questions": 9,
    "weight": 0.4,
    "rawTitle": "les sources d'erreurs et de biais en épidémiologie",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_069",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "principes de la surveillance épidémioloique",
    "badges": [],
    "questions": 13,
    "weight": 0.58,
    "rawTitle": "principes de la surveillance épidémioloique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_070",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "épidémiologie et prophylaxie des ISTs",
    "badges": [],
    "questions": 11,
    "weight": 0.49,
    "rawTitle": "épidémiologie et prophylaxie des ISTs",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_071",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Benmaamar",
    "title": "épidémiologie et prophylaxies des hépatites virales",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "épidémiologie et prophylaxies des hépatites virales",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_072",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "L’assurance Maladie au Maroc",
    "badges": [],
    "questions": 11,
    "weight": 0.49,
    "rawTitle": "L’assurance Maladie au Maroc",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_073",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Introduction aux systèmes de santé",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Introduction aux systèmes de santé",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_074",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Le système de santé au maroc",
    "badges": [],
    "questions": 28,
    "weight": 1.26,
    "rawTitle": "Le système de santé au maroc",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_075",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Mesure de l’état de santé:La transition epidémiologique",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Mesure de l’état de santé:La transition epidémiologique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_076",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Epidémiologie et prophylaxie des cancers",
    "badges": [],
    "questions": 10,
    "weight": 0.45,
    "rawTitle": "Epidémiologie et prophylaxie des cancers",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_077",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Introduction à l'economie de santé",
    "badges": [],
    "questions": 35,
    "weight": 1.57,
    "rawTitle": "Introduction à l'economie de santé",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_078",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Epidémiologie et prévention des maladies transmissibles",
    "badges": [],
    "questions": 11,
    "weight": 0.49,
    "rawTitle": "Epidémiologie et prévention des maladies transmissibles",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_079",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Programmes de lutte contre les maladies transmissibles: Leishmaniose",
    "badges": [],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "Programmes de lutte contre les maladies transmissibles: Leishmaniose",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_080",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Prophylaxie de la tuberculose au maroc",
    "badges": [],
    "questions": 5,
    "weight": 0.22,
    "rawTitle": "Prophylaxie de la tuberculose au maroc",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_081",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "Investigation d'un episode epidermique",
    "badges": [],
    "questions": 5,
    "weight": 0.22,
    "rawTitle": "Investigation d'un episode epidermique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_082",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Tachfouti",
    "title": "La prévention et le depistage",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "La prévention et le depistage",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_083",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. El Harch",
    "title": "Epidémiologie et surveillance de la grippe",
    "badges": [],
    "questions": 0,
    "weight": 0,
    "rawTitle": "Epidémiologie et surveillance de la grippe",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_084",
    "module": "MÉDECINE SOCIALE ET SANTÉ PUBLIQUE - ECONOMIE DE SANTÉ",
    "submodule": "Santé Publique",
    "prof": "Pr. Oumokhtar",
    "title": "Santé et environnement",
    "badges": [],
    "questions": 39,
    "weight": 1.75,
    "rawTitle": "Santé et environnement",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_085",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Bouazzaoui",
    "title": "Infections associées aux soins",
    "badges": [],
    "questions": 8,
    "weight": 0.36,
    "rawTitle": "Infections associées aux soins",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_086",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Bouazzaoui",
    "title": "Introduction à l’anesthésie",
    "badges": [],
    "questions": 7,
    "weight": 0.31,
    "rawTitle": "Introduction à l’anesthésie",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_087",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Kechna",
    "title": "Pancréatite aiguë grave",
    "badges": [],
    "questions": 19,
    "weight": 0.85,
    "rawTitle": "Pancréatite aiguë grave",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_088",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Houari",
    "title": "Les états de choc: généralités",
    "badges": [],
    "questions": 3,
    "weight": 0.13,
    "rawTitle": "Les états de choc: généralités",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_089",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Houari",
    "title": "L’état de choc anaphylactique",
    "badges": [],
    "questions": 6,
    "weight": 0.27,
    "rawTitle": "L’état de choc anaphylactique",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_090",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Houari",
    "title": "L'état de choc septique",
    "badges": [],
    "questions": 12,
    "weight": 0.54,
    "rawTitle": "L'état de choc septique",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_091",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Houari",
    "title": "L'état de choc hémorragique",
    "badges": [],
    "questions": 9,
    "weight": 0.4,
    "rawTitle": "L'état de choc hémorragique",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_092",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Houari",
    "title": "L’état de choc cardiogénique",
    "badges": [],
    "questions": 3,
    "weight": 0.13,
    "rawTitle": "L’état de choc cardiogénique",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_093",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Boukatta",
    "title": "Arrêt cardiaque chez l’adulte",
    "badges": [],
    "questions": 11,
    "weight": 0.49,
    "rawTitle": "Arrêt cardiaque chez l’adulte",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_094",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Boukatta",
    "title": "Insuffisance respiratoire aiguë chez l’adulte",
    "badges": [],
    "questions": 15,
    "weight": 0.67,
    "rawTitle": "Insuffisance respiratoire aiguë chez l’adulte",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_095",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Boukatta",
    "title": "Ventilation artificielle",
    "badges": [],
    "questions": 2,
    "weight": 0.09,
    "rawTitle": "Ventilation artificielle",
    "facultyStatus": "Effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": "17/09/2026"
  },
  {
    "id": "c_096",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les déséquilibres acido-basiques",
    "badges": [],
    "questions": 16,
    "weight": 0.72,
    "rawTitle": "Les déséquilibres acido-basiques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_097",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les déséquilibres glycémiques",
    "badges": [],
    "questions": 3,
    "weight": 0.13,
    "rawTitle": "Les déséquilibres glycémiques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_098",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les dyskaliémies",
    "badges": [],
    "questions": 8,
    "weight": 0.36,
    "rawTitle": "Les dyskaliémies",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_099",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les dyscalcémies",
    "badges": [],
    "questions": 8,
    "weight": 0.36,
    "rawTitle": "Les dyscalcémies",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_100",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Hémorragique en obstétrique",
    "badges": [],
    "questions": 6,
    "weight": 0.27,
    "rawTitle": "Hémorragique en obstétrique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_101",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les pathologies hypertensives au cours de la grossesse",
    "badges": [],
    "questions": 3,
    "weight": 0.13,
    "rawTitle": "Les pathologies hypertensives au cours de la grossesse",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_102",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Les dysnatrémies",
    "badges": [],
    "questions": 20,
    "weight": 0.9,
    "rawTitle": "Les dysnatrémies",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_103",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "Obstruction grave des voies aériennes chez l’enfant",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "Obstruction grave des voies aériennes chez l’enfant",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_104",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "CAT devant un coma non traumatique",
    "badges": [],
    "questions": 6,
    "weight": 0.27,
    "rawTitle": "CAT devant un coma non traumatique",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_105",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Harandou",
    "title": "La douleur",
    "badges": [],
    "questions": 2,
    "weight": 0.09,
    "rawTitle": "La douleur",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_106",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Berdai",
    "title": "L’intubation orotrachéale",
    "badges": [],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "L’intubation orotrachéale",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_107",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Berdai",
    "title": "Les abords vasculaires en urgence et en réanimation",
    "badges": [],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "Les abords vasculaires en urgence et en réanimation",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_108",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Berdai",
    "title": "Les envenimations scorpioniques",
    "badges": [],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "Les envenimations scorpioniques",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_109",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Berdai",
    "title": "Les envenimations ophidiennes",
    "badges": [],
    "questions": 1,
    "weight": 0.04,
    "rawTitle": "Les envenimations ophidiennes",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_110",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Intoxication aiguë",
    "badges": [],
    "questions": 22,
    "weight": 0.99,
    "rawTitle": "Intoxication aiguë",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_111",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Intoxication au monoxyde de carbone",
    "badges": [],
    "questions": 9,
    "weight": 0.4,
    "rawTitle": "Intoxication au monoxyde de carbone",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_112",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Intoxication aiguë aux pesticides organophosphorés",
    "badges": [],
    "questions": 6,
    "weight": 0.27,
    "rawTitle": "Intoxication aiguë aux pesticides organophosphorés",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_113",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Intoxication au paracétamol",
    "badges": [],
    "questions": 4,
    "weight": 0.18,
    "rawTitle": "Intoxication au paracétamol",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_114",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Intoxication par le Paraphénylène-Diamine Takaout",
    "badges": [],
    "questions": 5,
    "weight": 0.22,
    "rawTitle": "Intoxication par le Paraphénylène-Diamine Takaout",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_115",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Accidents d'électrisation",
    "badges": [],
    "questions": 7,
    "weight": 0.31,
    "rawTitle": "Accidents d'électrisation",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_116",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Derkaoui",
    "title": "Noyades",
    "badges": [],
    "questions": 0,
    "weight": 0,
    "rawTitle": "Noyades",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_117",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Shimi",
    "title": "PEC du traumatisme crânien grave à la phase initiale",
    "badges": [],
    "questions": 15,
    "weight": 0.67,
    "rawTitle": "PEC du traumatisme crânien grave à la phase initiale",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_118",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Shimi",
    "title": "Prise en charge du patient polytraumatisé",
    "badges": [],
    "questions": 25,
    "weight": 1.12,
    "rawTitle": "Prise en charge du patient polytraumatisé",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  },
  {
    "id": "c_119",
    "module": "URGENCES - RÉANIMATION",
    "submodule": "Urgences - Réanimation",
    "prof": "Pr. Shimi",
    "title": "Prise en charge du brûlé grave à la phase aiguë",
    "badges": [],
    "questions": 3,
    "weight": 0.13,
    "rawTitle": "Prise en charge du brûlé grave à la phase aiguë",
    "facultyStatus": "Non effectué",
    "sheetC1": false,
    "sheetC2": false,
    "facultyStatusDate": null
  }
]
};
